### PR TITLE
Better organize ship scene

### PR DESCRIPTION
**Pull request by jjay**
* split pops/coins into logic and view
* most flying objects now extends from flying_thing.gd
* export most flying objs props instead of consts
* collission now based on masks

### CODE REVIEW

**Comment by oliver-ruehl** [comment]
Great stuff! I'll be testing momentarily 💃

**Comment by oliver-ruehl** [comment]
What is the advantage of collision masks?

**Comment by jjay** [comment]
There is 2 main advantages - performance and logic organization.
Collidable objects can exist in any of 32 different layers. These layers are not visual, but more of a tagging system instead. A collidable can use these layers/tags to select with which objects it can collide (from [here](http://docs.godotengine.org/en/latest/classes/class_area2d.html#class-area2d-set-layer-mask)).

You can define the layer and mask from the inspector dock. So layer is the type of the object, and mask - is the type of objects this one should collide with. Engine makes binary `and` for detect collisions (a.layer&b.mask || a.mask&b.layer). The less object engine has to check - the better performance you achieve. 

I define three types of objects for ship scene: 1 - ship, 2 - player bullets, 3 - enemy objects. And define how they are collide with each other. In short, enemies should collides with ship and player bullets, but not with each other. And player do not collide with his bullets.



From my point of view, this is better logical organization, then custom methods/properties checks on each objects from gdscript. You know, the less code you write, the less errors you make =)

**Comment by jjay** [comment]
@oliver-ruehl, do you know about scene inheritance? It is one of my favorite features in Godot =)

**Comment by oliver-ruehl** [comment]
Thanks for explaining. Wow. This makes total sense.
The scene inheritance is known to me but I dont know it in detail (still havent read much of the documentation)

**Pull request merged**
